### ISSUE TITLE
Crash: worker send results in crash

### ISSUE THREAD

**Issue by asilvas** [godaddy/node-cluster-service#72]
```
cservice:  Worker worker.js(88554) exited, reason: restart
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: channel closed
    at ChildProcess.target.send (child_process.js:414:26)
    at sendHelper (cluster.js:676:8)
    at RoundRobinHandle.handoff (cluster.js:198:3)
    at RoundRobinHandle.distribute (cluster.js:184:20)
```

**Comment by asilvas** [comment]
Fixed in `v2` branch. Use `cluster-service@2.0.0-alpha3` or later.
